# Generated by Django 2.2 on 2021-08-30 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True)),
                ('cur_test', models.CharField(max_length=20)),
                ('next_test', models.CharField(max_length=20)),
                ('_status', models.CharField(max_length=10)),
                ('_pass', models.IntegerField()),
                ('_fail', models.IntegerField()),
            ],
        ),
    ]
