# Generated by Django 2.2 on 2021-08-30 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localtest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel',
            name='_fail',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='panel',
            name='_pass',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='panel',
            name='_status',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='panel',
            name='cur_test',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='panel',
            name='next_test',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
