# Generated by Django 2.2 on 2021-08-30 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localtest', '0002_auto_20210830_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel',
            name='_fail',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='panel',
            name='_pass',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
