# Generated by Django 2.2 on 2021-09-14 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localtest', '0003_auto_20210830_1455'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='panel',
            options={'verbose_name_plural': 'Panel'},
        ),
    ]
