# Generated by Django 2.2 on 2021-11-16 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localtest', '0004_auto_20210914_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Percent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.FloatField()),
            ],
        ),
    ]
