# Generated by Django 2.2 on 2021-11-16 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localtest', '0005_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='percent',
            name='percent',
            field=models.FloatField(default=0),
        ),
    ]
