# Generated by Django 2.2 on 2021-11-16 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localtest', '0006_auto_20211116_1443'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='percent',
            options={'verbose_name_plural': 'Percent'},
        ),
    ]
