# Generated by Django 2.2 on 2021-12-03 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localtest', '0008_auto_20211203_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel',
            name='_fail',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='panel',
            name='_pass',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
