# Generated by Django 2.2 on 2021-12-03 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localtest', '0011_auto_20211203_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='panel',
            name='_fail',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='panel',
            name='_pass',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
