# Generated by Django 2.2 on 2021-12-07 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localtest', '0012_auto_20211203_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='panel',
            name='_script',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
