# Generated by Django 2.2 on 2021-12-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localtest', '0013_panel__script'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panel',
            name='_script',
        ),
        migrations.AddField(
            model_name='percent',
            name='_script',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
